htmx/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('films.urls')),
    path('other/', include('other_functions.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

other_functions/urls.py
from django.urls import path
from . import views

app_name = 'other'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('modules/', views.modules, name='modules'),
]

other_functions/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name=models.CharField(max_length=128)

class Module(models.Model):
    name = models.CharField(max_length=128)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')

other_functions/views.py
from django.shortcuts import render
from .models import Course, Module
# Create your views here.

def courses(request):
    course = Course.objects.all()
    context = {'courses': course}

    return render(request, 'university.html', context)


def modules(request):
    course = request.GET.get('course')
    print(course)
    modules = Module.objects.filter(course=course)
    context = {'modules': modules}

    return render(request, 'partials/modules.html', context)

other_functions/templates/base_other.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>University</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- jQuery and Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
</head>
<body>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

other_functions/templates/university.html
{% extends 'base_other.html' %}

{% block content %}
    <select class="custom-select mb-4" name="course"
            hx-get="{% url 'other:modules' %}"
            hx-trigger="change"
            hx-target="#modules">
        {% for course in courses %}
            <option value="{{ course.pk }}">
                {{ course.name }}
            </option>
        {% endfor %}
    </select>

    <div id="modules">
        {% include 'partials/modules.html' %}
    </div>
{% endblock %}